[project]
name = "click-cli-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.0"
dependencies = [
    "click>=8.2.1",
    "plotly>=6.2.0",
]
